name: Ulatan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5412155177909881
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2710676356218755
  lightness: 0.30894059990532696
  saturation: 0.0724406773224473
  rhythmicContrast: 0.060489600989967585
purpose: []
