name: Ulatan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.58105
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e1e1'
    - '#010101'
    - '#bbbbbb'
    - '#5a5a5a'
    - '#858585'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
